import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import Link from 'next/link';
import { MainContainer } from '@/components/MainContainer';
import { GradientLayout } from '@/components/GradientLayout';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen dark`}>
        <GradientLayout className="min-h-screen">
          <header className="sticky top-0 z-50 flex justify-center items-center border-b border-border bg-transparent px-4 py-2 backdrop-blur">
            <MainContainer className="flex justify-center gap-7 flex-1">
              <Link className="text-2xl font-bold tracking-tight" href="/">
                Home
              </Link>
              <Link className="text-2xl font-bold tracking-tight" href="/">
                Chat
              </Link>
              <Link className="text-2xl font-bold tracking-tight" href="/">
                Get started
              </Link>
              <Link className="text-2xl font-bold tracking-tight" href="/">
                About
              </Link>
            </MainContainer>
          </header>
          {children}
        </GradientLayout>
      </body>
    </html>
  );
};

export default RootLayout;
